### ISSUE TITLE
install requirements in install.sh

### ISSUE THREAD

**Issue by hohmic** [jrkager/covid-southtyrol-widget#4]
add the installation of the requirements.txt for python modules to the installation sequence file

**Comment by jrkager** [comment]
A requirements.txt can already be found in the repo and should cover the modules for update-history.py as well (together with the standard modules). Do you think we should add a `conda create --name covid_history --file requirements.txt` command to install-updater.sh, and `conda activate covid_history` to loadvacc.sh?

**Comment by jrkager** [comment]
Affected code is now available in its own repo: https://github.com/jrkager/covid-vaccinations-italy
Reopen an issue there if you still find it to be an issue.
